### Data Exploration

In [28]:
import polars as pl
from prefect import flow
from supabase import create_client

In [29]:
@flow(log_prints=True)
def explain_flows():
    print("run any python code here!")
    print("encapsulate that business logic!")

if __name__ == "__main__":
    explain_flows()

11:40:16.905 | INFO    | prefect - Starting temporary server on http://127.0.0.1:8789
See https://docs.prefect.io/v3/concepts/server#how-to-guides for more information on running a dedicated Prefect server.

11:40:22.361 | INFO    | Flow run 'jovial-malkoha' - Beginning flow run 'jovial-malkoha' for flow 'explain-flows'

11:40:22.364 | INFO    | Flow run 'jovial-malkoha' - run any python code here!

11:40:22.370 | INFO    | Flow run 'jovial-malkoha' - encapsulate that business logic!

11:40:23.371 | INFO    | Flow run 'jovial-malkoha' - Finished in state Completed()

In [7]:
PUBLISHABLE_KEY = 'sb_publishable_719sq-GVEJ04QMlkdvDNKw_wE7Vqn5Y'
supabase = create_client("https://kmlebuzgwrkgujksuken.supabase.co", PUBLISHABLE_KEY)

---

#### Non-nucleoside reverse-transcriptase inhibitors

In [8]:
table1 = 'NNRTI_DataSet'
all_data = []
batch_size = 1000
offset = 0

In [9]:
while True:
    resp = supabase.table(table1).select("*").range(offset, offset + batch_size - 1).execute()
    all_data.extend(resp.data)
    if len(resp.data) < batch_size:
        break
    offset += batch_size

In [10]:
df1 = pl.DataFrame(all_data)
df1.shape

(2270, 325)

In [11]:
df1.head()

shape: (5, 325)
┌────────┬──────┬─────┬─────┬───┬──────┬──────┬──────┬─────────────────────────────────┐
│ SeqID  ┆ EFV  ┆ NVP ┆ ETR ┆ … ┆ P316 ┆ P317 ┆ P318 ┆ CompMutList                     │
│ ---    ┆ ---  ┆ --- ┆ --- ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---                             │
│ i64    ┆ str  ┆ str ┆ str ┆   ┆ str  ┆ str  ┆ str  ┆ str                             │
╞════════╪══════╪═════╪═════╪═══╪══════╪══════╪══════╪═════════════════════════════════╡
│ 205675 ┆ 25.0 ┆ 100 ┆ 1.2 ┆ … ┆ .    ┆ .    ┆ .    ┆ D67N, T69N, K70R, V90I, K103N,… │
│ 205679 ┆ 0.4  ┆ 0.4 ┆ 0.3 ┆ … ┆ .    ┆ .    ┆ .    ┆ M41L, D67N, T69D, V75T, V118I,… │
│ 216543 ┆ NA   ┆ NA  ┆ 1.2 ┆ … ┆ -    ┆ -    ┆ -    ┆ E399D                           │
│ 216546 ┆ NA   ┆ NA  ┆ 0.9 ┆ … ┆ -    ┆ -    ┆ -    ┆ G333E                           │
│ 216550 ┆ NA   ┆ NA  ┆ 9.5 ┆ … ┆ -    ┆ -    ┆ -    ┆ K101P, N348I                    │
└────────┴──────┴─────┴─────┴───┴──────┴──────┴──────┴─────────────────────────────────┘

---

#### Nucleoside analog reverse-transcriptase inhibitors

In [12]:
table2 = 'NRTI_DataSet'
all_data = []
batch_size = 1000
offset = 0

In [13]:
while True:
    resp = supabase.table(table2).select("*").range(offset, offset + batch_size - 1).execute()
    all_data.extend(resp.data)
    if len(resp.data) < batch_size:
        break
    offset += batch_size

In [14]:
df2 = pl.DataFrame(all_data)
df2.shape

(1867, 248)

In [15]:
df2.head()

shape: (5, 248)
┌───────┬─────┬─────┬─────┬───┬──────┬──────┬──────┬─────────────────────────────────┐
│ SeqID ┆ 3TC ┆ ABC ┆ AZT ┆ … ┆ P238 ┆ P239 ┆ P240 ┆ CompMutList                     │
│ ---   ┆ --- ┆ --- ┆ --- ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---                             │
│ i64   ┆ str ┆ str ┆ str ┆   ┆ str  ┆ str  ┆ str  ┆ str                             │
╞═══════╪═════╪═════╪═════╪═══╪══════╪══════╪══════╪═════════════════════════════════╡
│ 54191 ┆ 9.0 ┆ 2.4 ┆ 0.6 ┆ … ┆ -    ┆ -    ┆ -    ┆ K65R, S68G                      │
│ 60631 ┆ 9.7 ┆ 3.0 ┆ 0.5 ┆ … ┆ -    ┆ -    ┆ -    ┆ K65R, K122E, F214L, A272P, K27… │
│ 60636 ┆ 100 ┆ 8.5 ┆ 0.3 ┆ … ┆ -    ┆ -    ┆ -    ┆ L74V, K122E, M184V, F214L, A27… │
│ 54192 ┆ 6.3 ┆ 1.6 ┆ 0.5 ┆ … ┆ -    ┆ -    ┆ -    ┆ A62V, K65R                      │
│ 60630 ┆ 1.0 ┆ 0.9 ┆ 0.8 ┆ … ┆ -    ┆ -    ┆ -    ┆ K122E, F214L, A272P, K277R, M3… │
└───────┴─────┴─────┴─────┴───┴──────┴──────┴──────┴─────────────────────────────────┘

---

#### Capsid assembly inhibitors

In [16]:
table3 = 'CAI_DataSet'
all_data = []
batch_size = 1000
offset = 0

In [17]:
while True:
    resp = supabase.table(table3).select("*").range(offset, offset + batch_size - 1).execute()
    all_data.extend(resp.data)
    if len(resp.data) < batch_size:
        break
    offset += batch_size

In [18]:
df3 = pl.DataFrame(all_data)
df3.shape

(71, 234)

In [19]:
df3.head()

shape: (5, 234)
┌────────┬──────┬─────┬─────┬───┬──────┬──────┬──────┬─────────────┐
│ SeqID  ┆ LEN  ┆ P1  ┆ P2  ┆ … ┆ P229 ┆ P230 ┆ P231 ┆ CompMutList │
│ ---    ┆ ---  ┆ --- ┆ --- ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---         │
│ i64    ┆ f64  ┆ str ┆ str ┆   ┆ str  ┆ str  ┆ str  ┆ str         │
╞════════╪══════╪═════╪═════╪═══╪══════╪══════╪══════╪═════════════╡
│ 749359 ┆ 6.0  ┆ -   ┆ -   ┆ … ┆ -    ┆ -    ┆ -    ┆ Q67H        │
│ 749360 ┆ 22.0 ┆ -   ┆ -   ┆ … ┆ -    ┆ -    ┆ -    ┆ N74D        │
│ 749361 ┆ 24.0 ┆ -   ┆ -   ┆ … ┆ -    ┆ -    ┆ -    ┆ K70N        │
│ 749362 ┆ 32.0 ┆ -   ┆ -   ┆ … ┆ -    ┆ -    ┆ -    ┆ Q67H, N74S  │
│ 749363 ┆ 62.0 ┆ -   ┆ -   ┆ … ┆ -    ┆ -    ┆ -    ┆ Q67H, T107N │
└────────┴──────┴─────┴─────┴───┴──────┴──────┴──────┴─────────────┘

---

#### Protease Inhibitors

In [20]:
table4 = 'PI_DataSet'
all_data = []
batch_size = 1000
offset = 0

In [21]:
while True:
    resp = supabase.table(table4).select("*").range(offset, offset + batch_size - 1).execute()
    all_data.extend(resp.data)
    if len(resp.data) < batch_size:
        break
    offset += batch_size

In [22]:
df4 = pl.DataFrame(all_data)
df4.shape

(2171, 109)

In [23]:
df4.head()

shape: (5, 109)
┌───────┬─────┬─────┬─────┬───┬─────┬─────┬─────┬──────────────────────────────┐
│ SeqID ┆ FPV ┆ ATV ┆ IDV ┆ … ┆ P97 ┆ P98 ┆ P99 ┆ CompMutList                  │
│ ---   ┆ --- ┆ --- ┆ --- ┆   ┆ --- ┆ --- ┆ --- ┆ ---                          │
│ i64   ┆ str ┆ str ┆ str ┆   ┆ str ┆ str ┆ str ┆ str                          │
╞═══════╪═════╪═════╪═════╪═══╪═════╪═════╪═════╪══════════════════════════════╡
│ 12862 ┆ 0.8 ┆ NA  ┆ 1.2 ┆ … ┆ -   ┆ -   ┆ -   ┆ D30N, M46I, R57G, L63P, N88D │
│ 13259 ┆ 0.1 ┆ NA  ┆ 2.9 ┆ … ┆ -   ┆ -   ┆ -   ┆ M46L, R57G, L63P, V77I, N88S │
│ 12863 ┆ 3.0 ┆ NA  ┆ 2.8 ┆ … ┆ -   ┆ -   ┆ -   ┆ M46I, R57G, L63P, V82T, I84V │
│ 13257 ┆ 0.1 ┆ NA  ┆ 2.3 ┆ … ┆ -   ┆ -   ┆ -   ┆ M46L, R57G, L63P, N88S       │
│ 13258 ┆ 0.1 ┆ NA  ┆ 3.0 ┆ … ┆ -   ┆ -   ┆ -   ┆ R57G, L63P, V77I, N88S       │
└───────┴─────┴─────┴─────┴───┴─────┴─────┴─────┴──────────────────────────────┘

---

#### Integrase inhibitors

In [24]:
table5 = 'INI_DataSet'
all_data = []
batch_size = 1000
offset = 0

In [25]:
while True:
    resp = supabase.table(table5).select("*").range(offset, offset + batch_size - 1).execute()
    all_data.extend(resp.data)
    if len(resp.data) < batch_size:
        break
    offset += batch_size

In [26]:
df5 = pl.DataFrame(all_data)
df5.shape

(846, 295)

In [27]:
df5.head()

shape: (5, 295)
┌────────┬──────┬──────┬─────┬───┬──────┬──────┬──────┬─────────────┐
│ SeqID  ┆ RAL  ┆ EVG  ┆ DTG ┆ … ┆ P286 ┆ P287 ┆ P288 ┆ CompMutList │
│ ---    ┆ ---  ┆ ---  ┆ --- ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---         │
│ i64    ┆ str  ┆ str  ┆ str ┆   ┆ str  ┆ str  ┆ str  ┆ str         │
╞════════╪══════╪══════╪═════╪═══╪══════╪══════╪══════╪═════════════╡
│ 219526 ┆ 0.9  ┆ 7.6  ┆ 0.3 ┆ … ┆ -    ┆ -    ┆ -    ┆ T66A        │
│ 219527 ┆ 1.1  ┆ 4.1  ┆ 1.0 ┆ … ┆ -    ┆ -    ┆ -    ┆ S147G       │
│ 219528 ┆ 15.0 ┆ 4.9  ┆ 0.4 ┆ … ┆ -    ┆ -    ┆ -    ┆ Q148H       │
│ 219529 ┆ 37.0 ┆ 94.0 ┆ 1.5 ┆ … ┆ -    ┆ -    ┆ -    ┆ Q148K       │
│ 219530 ┆ 29.0 ┆ 92.0 ┆ 1.1 ┆ … ┆ -    ┆ -    ┆ -    ┆ Q148R       │
└────────┴──────┴──────┴─────┴───┴──────┴──────┴──────┴─────────────┘

---